app/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path("table/", views.TableView.as_view(), name="table"),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('hydropost/', HydropostView.as_view(), name='hydropost'),
    path('hydropost-mode/', HydropostModeView.as_view(), name='hydropost-mode'),
    path("meteostation/", MeteostationView.as_view(), name="meteostation"),
    path("meteostation-parameter/", MeteostationParameterView.as_view(), name="meteostation-parameter"),
    path("import/", ImportView.as_view(), name="import")
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='index'),
    path("common/", include(("common.urls", "common"), namespace="common")),
    path('hydrogeological/', include(('hydrogeological.urls', 'hydrogeological'), namespace='hydrogeological'), name='hydrogeological'),
    path('hydromelioratical/', include(('hydromelioratical.urls', 'hydromelioratical'), namespace='hydromelioratical'), name='hydromelioratical'),
    path('hydrometeorological/', include(('hydrometeorological.urls', 'hydrometeorological'), namespace='hydrometeorological'), name='hydrometeorological'),
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hydrometeorological/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('hydrometria/', views.HydrometriaView.as_view(), name='hydrometria'),
    path('meteorology/', views.MeteorologyView.as_view(), name='meteorology'),
    path('show/hydropost-levels/', views.HydrometriaShowView.as_view(), name='hydropost-show'),
    path('show/hydropost-levels/one-year', views.GraphOneYear.as_view(), name='hydropost-one-year'),
    path('show/hydropost-levels/compare-year', views.GraphCompareTwoYears.as_view(), name='hydropost-compare-year'),
    path('show/meteostation-levels/', views.MeteostationShowView.as_view(), name='meteostation-show'),
    path('show/meteostation-levels/one-year', views.MeteostationGraphOneYear.as_view(), name='meteostation-one-year'),
    path('show/meteostation-levels/compare-year', views.MeteostationGraphCompareTwoYears.as_view(), name='meteostation-compare-year'),
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hydrometeorological/models.py
from django.db import models
from common.models import Region

# Create your models here.
class ObjectType(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Mode(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return str(self.name)
    
class Hydropost(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Gidropost'
        verbose_name_plural = 'Gidropostlar'

class HydropostValue(models.Model):
    hydropost = models.ForeignKey(Hydropost, on_delete=models.CASCADE, related_name='hydropost_values', verbose_name='Gidropost nomi')
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, related_name='hydropost_values', null=True, verbose_name='Viloyat')
    object_type = models.ForeignKey(ObjectType, on_delete=models.SET_NULL, related_name='hydropost_values', null=True, verbose_name="Suv ob'ekti turi"),
    mode = models.ForeignKey(Mode, on_delete=models.SET_NULL, related_name='hydropost_values', null=True, verbose_name='Rejim turi')
    
    year = models.IntegerField(verbose_name='Yil')
    I = models.FloatField(blank=True, null=True, verbose_name='Yanvar')
    II = models.FloatField(blank=True, null=True, verbose_name='Fevral')
    III = models.FloatField(blank=True, null=True, verbose_name='Mart')
    IV = models.FloatField(blank=True, null=True, verbose_name='Aprel')
    V = models.FloatField(blank=True, null=True, verbose_name='May')
    VI = models.FloatField(blank=True, null=True, verbose_name='Iyun')
    VII = models.FloatField(blank=True, null=True, verbose_name='Iyul')
    VIII = models.FloatField(blank=True, null=True, verbose_name='Avgust')
    IX = models.FloatField(blank=True, null=True, verbose_name='Sentyabr')
    X = models.FloatField(blank=True, null=True, verbose_name='Oktyabr')
    XI = models.FloatField(blank=True, null=True, verbose_name='Noyabr')
    XII = models.FloatField(blank=True, null=True, verbose_name='Dekabr')
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.hydropost.name + ' - ' + str(self.mode) + ' - ' + str(self.year)
    
    class Meta:
        verbose_name = 'Gidrometriya'
        verbose_name_plural = 'Gidrometriya'
    
class Meteostation(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Meteostansiya'
        verbose_name_plural = 'Meteostansiyalar'
    
class Parameter(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class MeteostationValue(models.Model):
    meteostation = models.ForeignKey(Meteostation, on_delete=models.CASCADE, related_name='meteostation_values')
    parameter = models.ForeignKey(Parameter, on_delete=models.SET_NULL, related_name='meteostation_values', null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, related_name='meteostation_values', null=True)

    year = models.IntegerField(verbose_name='Yil')
    I = models.FloatField(blank=True, null=True, verbose_name='Yanvar')
    II = models.FloatField(blank=True, null=True, verbose_name='Fevral')
    III = models.FloatField(blank=True, null=True, verbose_name='Mart')
    IV = models.FloatField(blank=True, null=True, verbose_name='Aprel')
    V = models.FloatField(blank=True, null=True, verbose_name='May')
    VI = models.FloatField(blank=True, null=True, verbose_name='Iyun')
    VII = models.FloatField(blank=True, null=True, verbose_name='Iyul')
    VIII = models.FloatField(blank=True, null=True, verbose_name='Avgust')
    IX = models.FloatField(blank=True, null=True, verbose_name='Sentyabr')
    X = models.FloatField(blank=True, null=True, verbose_name='Oktyabr')
    XI = models.FloatField(blank=True, null=True, verbose_name='Noyabr')
    XII = models.FloatField(blank=True, null=True, verbose_name='Dekabr')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.meteostation.name + ' - ' + str(self.parameter) + ' - ' + str(self.year)
    
    class Meta:
        verbose_name = 'Meteorologiya'
        verbose_name_plural = 'Meteorologiya'

hydrogeological/forms.py
import datetime
from django import forms 
from hydrogeological.models import Well, Coordinate, WaterLevel



class PasportForm(forms.ModelForm):
    
    lat_degree = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    lat_minute = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    lat_second = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    lon_degree = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    lon_minute = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    lon_second = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    x = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    y = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)
    
    created_at = forms.DateField(
        required=True,
        widget=forms.DateInput(
            format="%Y-%m-%d", 
            attrs={
                'class': 'form-control', 
                'type': 'date',
                'value': datetime.datetime.now().strftime("%Y-%m-%d")
                }
        ),
        input_formats=["%Y-%m-%d"]
    )
    
    class Meta:
        model = Well
        fields = [
            'organization', 'well_number', 'station', 'type', 'region', 'district', 'address', 'location', 'created_at',
            'lat_degree', 'lat_minute', 'lat_second', 'lon_degree', 'lon_minute', 'lon_second', 'x', 'y'
            ]
    
        widgets = {
            'organization': forms.Select(attrs={'class': 'form-control', 'required':'required'}),
            'well_number': forms.NumberInput(attrs={'class': 'form-control', 'required':'required'}),
            'station': forms.Select(attrs={'class': 'form-control', 'required':'required'}),
            'type': forms.Select(attrs={'class': 'form-control', 'required':'required'}),
            'region': forms.Select(attrs={'class': 'form-control region_select', 'required':'required'}),
            'district': forms.Select(attrs={'class': 'form-control district_select', 'required':'required'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'required':'required'}),
            'location': forms.Select(attrs={'class': 'form-control', 'required':'required'}),
            'created_at': forms.DateInput(attrs={'class': 'form-control', 'required':'required'}),
        }
    
    def save(self, commit=True):
        well_instance = super().save(commit=False)
        if commit:
            well_instance.save()
        
        coordinate_data = {
            'lat_degree': self.cleaned_data.get('lat_degree'),
            'lat_minute': self.cleaned_data.get('lat_minute'),
            'lat_second': self.cleaned_data.get('lat_second'),
            'lon_degree': self.cleaned_data.get('lon_degree'),
            'lon_minute': self.cleaned_data.get('lon_minute'),
            'lon_second': self.cleaned_data.get('lon_second'),
            'x': self.cleaned_data.get('x'),
            'y': self.cleaned_data.get('y'),
            'well': well_instance
        }
        
        Coordinate.objects.create(**coordinate_data)
        
        return well_instance
    
class WaterLevelForm(forms.ModelForm):
    well = forms.ModelChoiceField(
        queryset=Well.objects.all()
    )
    class Meta:
        model = WaterLevel
        fields = '__all__'

hydrometeorological/forms.py
import datetime
from django import forms 
from .models import *
from common.models import Region

class HydrometriaForm(forms.ModelForm):
    
    hydropost = forms.ModelChoiceField(
        queryset=Hydropost.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    region = forms.ModelChoiceField(
        queryset=Region.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    object_type = forms.ModelChoiceField(
        queryset=ObjectType.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    mode = forms.ModelChoiceField(
        queryset=Mode.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    
    class Meta:
        model = HydropostValue
        fields = ['I', 'II', 'III', 'IV', 'IX', 'V', 'VI', 'VII', 'VIII', 'X', 'XI', 'XII', 'hydropost', 'mode', 'region', 'year', 'object_type']

class MeteorologyForm(forms.ModelForm):

    meteostation = forms.ModelChoiceField(
        queryset=Meteostation.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    parameter = forms.ModelChoiceField(
        queryset=Parameter.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    region = forms.ModelChoiceField(
        queryset=Region.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = MeteostationValue
        fields = ['I', 'II', 'III', 'IV', 'IX', 'V', 'VI', 'VII', 'VIII', 'X', 'XI', 'XII', 'meteostation', 'parameter', 'region', 'year']

templates/hydrometeorological/show/ground_water_level.html
{% extends "base.html" %} {% load static %} {% block title %}Yerosti suvlari sathi rejimi{% endblock %} {% block styles %}
{% load custom_tags %}
<style>
  .blue {
    color: #012970;
  }
  tbody {
      display:block;
      height:60vh;
      overflow:auto;
      width: 100%;
  }
  thead, tbody tr {
      display:table;
      width:100%;
      table-layout:fixed;
  }
  thead{
    width: calc(100% - 15px);
  }
    /* width */
  tbody::-webkit-scrollbar {
    width: 15px;
    position: fixed;
  }

  /* Track */
  tbody::-webkit-scrollbar-track {
    background-color: hsl(250 15% 93%);
    border-radius: 9999px;
    position: fixed;
  }
  
  /* Handle */
  tbody::-webkit-scrollbar-thumb {
    
    border: 4px solid rgba(0, 0, 0, 0);
    background-clip: padding-box;
    border-radius: 9999px;
    background-color: #AAAAAA;
  }

  /* Handle on hover */
  tbody::-webkit-scrollbar-thumb:hover {
    background-color: rgb(0,0,0,0.2); 
  }

  .fullscreen-btn {
    visibility: hidden;
    position: absolute;
    bottom: 15px;
    right: 35px;
    z-index: 10;
  }
</style>
{% endblock styles %} {% block content %} 

{% include "components/loading_modal.html" %}
<main>
  <section class="container-fluid">
    <div class="row">
      <div class="col-12 col-lg-3" style='height:88vh'>

        <div class="card rounded-2 h-100 mb-0 overflow-hidden">
          <div class="card-body" style='display: flex;flex-direction: column;'>
  
            <div class="row mt-3 mb-3">
              <label for="station" class="col-sm-6 col-form-label">Gidropost nomi</label>
              <div class="col-sm-6 d-flex align-items-center">
                <select class="form-control hydropost_select" id="station">
                </select>
              </div>
            </div>
  
            <div class="row mb-3">
              <label for="id_mode" class="col-sm-6 col-form-label">Rejim turi</label>
              <div class="col-sm-6 d-flex align-items-center">
                <select class="form-control mode_select" id="id_mode" required>
                </select>
              </div>
            </div>

            {% comment %} <div class="buttons-overlay"></div> {% endcomment %}

            <div class="row mb-3 blue mt-auto">
              <h5>Butun davr uchun malumotlar</h5>
            </div>

            <dl class="row mb-3">
              <dt class="col-sm-6">Min</dt>
              <dd class="col-sm-6 mb-0" id='all_time_min'></dd>
      
              <dt class="col-sm-6">Max</dt>
              <dd class="col-sm-6 mb-0" id='all_time_max'></dd>
      
              <dt class="col-sm-6">O'rtacha</dt>
              <dd class="col-sm-6 mb-0" id='all_time_avg'></dd>
      
              <dt class="col-sm-6">Dispersiya</dt>
              <dd class="col-sm-6 mb-0" id='all_time_variance'></dd>

              <dt class="col-sm-6">Standart og'ish</dt>
              <dd class="col-sm-6 mb-0" id='all_time_std_dev'></dd>

              <dt class="col-sm-6">O'zgarish koeffitsienti</dt>
              <dd class="col-sm-6 mb-0" id='all_time_cv'></dd>
            </dl>
            
            

              <div class="row mb-3 position-relative ">
                
                
                <div class="col-6">
                  <div class="row mb-3"><input class='form-control add-spin' type='number' id='oneyear' min='0'></input></div>
                  <div class="row"><input class='form-control add-spin' type='number' id='secondyear' min='0'></input></div>
                </div>
                <div class="col-6">
                  <div class="row mb-3">
                    <div class="col-12">
                      <button class='btn btn-primary w-100' type='button' id='graphOneYear'>Grafik</button>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col-12">
                      <button class='btn btn-primary w-100'  type='button' id='graphCompare'>Solishtirma Grafik</button>
                    </div>
                  </div>
                  <button class='btn btn-primary' type='button' id='heatmap'>Heatmap</button>
                </div>
              </div>
    
    
            
          </div>
        </div>

      </div>
      <div class="col-12 col-lg-9" style='height:88vh'>

        <div class="card rounded-2 h-100 mb-0 overflow-hidden">
          <div class="card-body">
              <div class="row my-3 text-center blue"><h1>Gidropost ma'lumotlari</h1></div>
              <div class="row">
                <div class="col-lg-4">
                  <div class="row mb-3">
                    <div class="col-sm-8 d-flex align-items-center">
                      <select class="form-select" id="start_month">
                        <option value="">---------</option>
                        <option value="1">Yanvar</option>
                        <option value="2">Fevral</option>
                        <option value="3">Mart</option>
                        <option value="4">Aprel</option>
                        <option value="5">May</option>
                        <option value="6">Iyun</option>
                        <option value="7">Iyul</option>
                        <option value="8">Avgust</option>
                        <option value="9">Sentyabr</option>
                        <option value="10">Oktyabr</option>
                        <option value="11">Noyabr</option>
                        <option value="12">Dekabr</option>
                      </select>
                    </div>
                    <div class="col-sm-4 d-flex align-items-center">
                      <input type="number" name="start_year" class='form-control add-spin' id='start_year' value='1900'>
                    </div>
                  </div>
                </div>
                <div class="col-lg-2">
                  <hr class='w-50 mx-auto' style='height:3px;border-width:0;color:black;background-color:black'>
                </div>
                <div class="col-lg-4">
                  <div class="row mb-3">
                    
                    <div class="col-sm-8 d-flex align-items-center">
                      <select class="form-select" id="end_month">
                        <option value="">---------</option>
                        <option value="1">Yanvar</option>
                        <option value="2">Fevral</option>
                        <option value="3">Mart</option>
                        <option value="4">Aprel</option>
                        <option value="5">May</option>
                        <option value="6">Iyun</option>
                        <option value="7">Iyul</option>
                        <option value="8">Avgust</option>
                        <option value="9">Sentyabr</option>
                        <option value="10">Oktyabr</option>
                        <option value="11">Noyabr</option>
                        <option value="12">Dekabr</option>
                      </select>
                    </div>
                    <div class="col-sm-4 d-flex align-items-center">
                      <input type="number" name="end_year" class='form-control add-spin' id='end_year' value='1900'>
                    </div>
                    
                  </div>
                </div>
                <div class="col-lg-2">
                    <button type="button" class="btn btn-primary ms-auto" id='filter-button'>Ko'rsatish</button>
                </div>
                
              </div>
              
              <div class="row my-3">
                <div class="table-responsive position-relative" >
                  <button class="btn btn-primary fullscreen-btn" id="fullscreenBtn" type='button'>
                    <i class="bi bi-arrows-fullscreen"></i>
                  </button>
                  <table class="table table-bordered water_level_table table-sm mb-0">
                    <thead class="table-light">
                      <tr>
                        <th scope="col">Yil</th>
                        <th scope="col">I</th>
                        <th scope="col">II</th>
                        <th scope="col">III</th>
                        <th scope="col">IV</th>
                        <th scope="col">V</th>
                        <th scope="col">VI</th>
                        <th scope="col">VII</th>
                        <th scope="col">VIII</th>
                        <th scope="col">IX</th>
                        <th scope="col">X</th>
                        <th scope="col">XI</th>
                        <th scope="col">XII</th>
                        <th scope="col">O'rtacha</th>
                        <th scope="col" style='font-size:0.9rem'>Amplituda</th>
                      </tr>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
                
              </div>
    
    
    
          </div>
        </div>

      </div>
    </div>
  </section>
</main>

{% endblock content %}

{% block scripts %}

{% include "components/message-success.html" with messages=messages form=form %}
{% include "components/loading_modal.html" %}
{% include "components/modals.html" with modal='fullscreenmodal' %}
{% include "components/modals.html" with modal='imagedownloadmodal' %}
<script src="{% static 'app/assets/js/helpers.js' %}"></script>
<script src="{% static 'app/assets/js/gidro-levels-show.js' %}"></script>

{% endblock scripts %}

templates/hydrometeorological/show/pasport.html
{% extends "base.html" %} {% load static %} {% block title %}Kuzatuv-burg'u qudug'i pasporti{% endblock %} {% block styles %}
<style>
  .blue {
    color: #012970;
  }
</style>
{% endblock styles %} {% block content %} 
<main>
  <section class="container-fluid">
    <div class="card col-12 rounded-4">
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          <!-- Section -->
          <section class="col-lg-6 col-12 px-4 my-4">

            <div class="row mb-3">
              <label for="station" class="col-sm-6 col-form-label col-form-label-lg">Ekspeditsiyalar nomi</label>
              <div class="col-sm-6 d-flex align-items-center">
                <select class="form-control station_select">
                </select>
              </div>
            </div>

            <div class="row mb-3">
              <label for="id_well" class="col-sm-6 col-form-label col-form-label-lg">Kuzatuv-burg'u qudug'i raqami</label>
              <div class="col-sm-6 d-flex align-items-center">
                <select class="form-control well_select" id="id_well" name='well' required>
                </select>
              </div>
            </div>

          </section><!-- End Section -->
          <div class="wrapper" style="visibility: hidden;">
            <div class="row my-3 text-center blue"><h1>Kuzatuv-burg'u qudug'i pasporti</h1></div>
            <div class="row">
              <!-- Section -->
              <section class="col-lg-6 col-12 px-4">
                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Qaysi davlat tashkilotiga mansubligi</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="organization"></div>
                </div>

                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Qaysi ekspeditsiya</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="expedicion"></div>
                </div>
              </section>
              <!-- End Section -->

              <!-- Section -->
              <section class="col-lg-6 col-12 px-4">
                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Kuzatuv qudug'i raqami</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="well_number"></div>
                </div>

                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Kuzatuv burg'u qudug'ining turi</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="type"></div>
                </div>
              </section>
              <!-- End Section -->
            </div>

            <div class="row my-3 text-center blue"><h1>Ma'muriy joylashuvi</h1></div>
            <div class="row">
              <!-- Section -->
              <section class="col-lg-6 col-12 px-4">
                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Viloyat nomi</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="region"></div>
                </div>

                <div class="row mb-3">
                  <label for="country" class="col-sm-6 col-form-label col-form-label-lg">Tuman nomi</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="district"></div>
                </div>

                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Mo'ljal</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="address"></div>
                </div>

                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Joylashuv o'rni</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="location"></div>
                </div>
              </section>
              <!-- End Section -->

              <!-- Section -->
              <section class="col-xxl-6 col-12 px-4">
                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Kuzatuv burg'u qudug'ining koordinatasi</label>
                  <div class="col-sm-6 d-flex align-items-center"></div>
                </div>

                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Shimoliy kenglik</label>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="lat_degree">
                      <span class="input-group-text">°</span>
                    </div>
                  </div>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="lat_minute">
                      <span class="input-group-text">'</span>
                    </div>
                  </div>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="lat_second">
                      <span class="input-group-text">"</span>
                    </div>
                  </div>
                </div>

                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">Sharqiy uzunlik</label>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="lon_degree">
                      <span class="input-group-text">°</span>
                    </div>
                  </div>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="lon_minute">
                      <span class="input-group-text">'</span>
                    </div>
                  </div>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="lon_second">
                      <span class="input-group-text">"</span>
                    </div>
                  </div>
                </div>

                <div class="row mb-3">
                  <label class="col-sm-6 col-form-label col-form-label-lg">[x; y]</label>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="x">
                      <span class="input-group-text">x</span>
                    </div>
                  </div>
                  <div class="col-sm-2 d-flex align-items-center">
                    <div class="input-group">
                      <input type="number" class="form-control" disabled id="y">
                      <span class="input-group-text">y</span>
                    </div>
                  </div>
                  <div class="col-sm-2 d-flex align-items-center"></div>
                </div>

                <div class="row mb-5">
                  <label class="col-sm-6 col-form-label col-form-label-lg">To'ldirilgan sanasi</label>
                  <div class="col-sm-6 d-flex align-items-center col-form-label-lg" id="created_at"></div>
                </div>
              </section>
              <!-- End Section -->
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</main>

{% endblock content %} {% block scripts %} {% include "components/message-success.html" with messages=messages form=form %} {% include "components/modals.html" with modal='hydrogeological' %}
{% include "components/loading_modal.html" %}
<script src="{% static 'app/assets/js/hydromelioratical-show.js' %}"></script>

{% endblock scripts %}