app/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path("table/", views.TableView.as_view(), name="table"),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('hydropost/', HydropostView.as_view(), name='hydropost'),
    path('hydropost-mode/', HydropostModeView.as_view(), name='hydropost-mode'),
    path("meteostation/", MeteostationView.as_view(), name="meteostation"),
    path("meteostation-parameter/", MeteostationParameterView.as_view(), name="meteostation-parameter"),
    path("import/", ImportView.as_view(), name="import")
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='index'),
    path("common/", include(("common.urls", "common"), namespace="common")),
    path('hydrogeological/', include(('hydrogeological.urls', 'hydrogeological'), namespace='hydrogeological'), name='hydrogeological'),
    path('hydromelioratical/', include(('hydromelioratical.urls', 'hydromelioratical'), namespace='hydromelioratical'), name='hydromelioratical'),
    path('hydrometeorological/', include(('hydrometeorological.urls', 'hydrometeorological'), namespace='hydrometeorological'), name='hydrometeorological'),
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hydrogeological/urls.py
from . import views
from . import shows
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('pasport/', views.PasportView.as_view(), name='pasport'),
    path('water-level/', views.GroundWaterLevelView.as_view(), name='water-level'),
    path('water-chemic/', views.GroundWaterChemicalView.as_view(), name='water-chemic'),
    path('station/', views.station, name='station'),
    path('well/', views.well, name='station'),
    path('import/', views.ImportView.as_view(), name='import'),
    path('station-well/', views.station_well, name='station-well'),
    
    path('show/', shows.HomeView.as_view(), name='home-show'),
    path('show/pasport/', shows.PasportView.as_view(), name='pasport-show'),
    path('show/water-level/', shows.GroundWaterLevelView.as_view(), name='water-level-show'),
    path('show/water-level/heatmap', shows.HeatMap.as_view(), name='water-level-heatmap'),
    path('show/water-level/one-year', shows.GraphOneYear.as_view(), name='water-level-one-year'),
    path('show/water-level/compare-year', shows.GraphCompareTwoYears.as_view(), name='water-level-compare-year'),
    
    path('lithologic/', views.LithologicView.as_view(), name='lithologic'),
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hydrometeorological/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('hydrometria/', views.HydrometriaView.as_view(), name='hydrometria'),
    path('meteorology/', views.MeteorologyView.as_view(), name='meteorology'),
    path('show/hydropost-levels/', views.HydrometriaShowView.as_view(), name='hydropost-show'),
    path('show/hydropost-levels/one-year', views.GraphOneYear.as_view(), name='hydropost-one-year'),
    path('show/hydropost-levels/compare-year', views.GraphCompareTwoYears.as_view(), name='hydropost-compare-year'),
    path('show/meteostation-levels/', views.MeteostationShowView.as_view(), name='meteostation-show'),
    path('show/meteostation-levels/one-year', views.MeteostationGraphOneYear.as_view(), name='meteostation-one-year'),
    path('show/meteostation-levels/compare-year', views.MeteostationGraphCompareTwoYears.as_view(), name='meteostation-compare-year'),
] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/aside.html
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

  <ul class="sidebar-nav" id="sidebar-nav">

    <li class="nav-item">
      <a class="nav-link {% if aside != "main-home" %}collapsed{% endif %}" href="{% url "home" %}">
        <i class="bi bi-grid"></i>
        <span>Bosh sahifa</span>
      </a>
    </li><!-- End Dashboard Nav -->

    <li class="nav-heading mt-4">Yangi ma'lumot kiritish</li>

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#hydrogeological-nav" data-bs-toggle="collapse" href="#">
        <span>Gidrogeologik</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="hydrogeological-nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url "hydrogeological:pasport" %}">
            <i class="bi bi-circle"></i><span>Kuzatuv-burg'u qudug'i pasporti</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydrogeological:water-level" %}">
            <i class="bi bi-circle"></i><span>Yerosti suvlari sathi rejimi</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydrogeological:water-chemic" %}">
            <i class="bi bi-circle"></i><span>Yerosti suvlari kimyoviy tarkibi</span>
          </a>
        </li>
      </ul>
    </li><!-- End Components Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#hydromelioratical-nav" data-bs-toggle="collapse" href="#">
        <span>Gidromeliorativ</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="hydromelioratical-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url "hydromelioratical:pasport" %}">
            <i class="bi bi-circle"></i><span>Gidromeliorativ ob'ekt pasporti</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydromelioratical:water-level" %}">
            <i class="bi bi-circle"></i><span>Yerosti suvlari sathi rejimi</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydromelioratical:water-chemic" %}">
            <i class="bi bi-circle"></i><span>Yerosti suvlari kimyoviy tarkibi</span>
          </a>
        </li>
      </ul>
    </li><!-- End Components Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#hydrometeorological-nav" data-bs-toggle="collapse" href="#">
        <span>Gidrometeorologik</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="hydrometeorological-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url "hydrometeorological:hydrometria" %}">
            <i class="bi bi-circle"></i><span>Gidrometriya</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydrometeorological:meteorology" %}">
            <i class="bi bi-circle"></i><span>Meteorologiya</span>
          </a>
        </li>
      </ul>
    </li><!-- End Components Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url "hydrogeological:lithologic" %}">
        <span>Litologik</span></i>
      </a>
    </li><!-- End Components Nav -->

    <li class="nav-heading mt-5">Mavjud ma'lumotlar ombori</li>

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#hydrogeological-show-nav" data-bs-toggle="collapse" href="#">
        <span>Gidrogeologik</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="hydrogeological-show-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url "hydrogeological:pasport-show" %}">
            <i class="bi bi-circle"></i><span>Kuzatuv-burg'u qudug'i pasporti</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydrogeological:water-level-show" %}">
            <i class="bi bi-circle"></i><span>Yerosti suvlari sathi rejimi</span>
          </a>
        </li>
      </ul>
    </li><!-- End Components Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#hydromelioratical-show-nav" data-bs-toggle="collapse" href="#">
        <span>Gidromeliorativ</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="hydromelioratical-show-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url "hydromelioratical:pasport-show" %}">
            <i class="bi bi-circle"></i><span>Gidromeliorativ ob'ekt pasporti</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydromelioratical:water-level-show" %}">
            <i class="bi bi-circle"></i><span>Yerosti suvlari sathi rejimi</span>
          </a>
        </li>
      </ul>
    </li><!-- End Components Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#hydrometeorological-show-nav" data-bs-toggle="collapse" href="#">
        <span>Gidrometeorologik</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="hydrometeorological-show-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url "hydrometeorological:hydropost-show" %}">
            <i class="bi bi-circle"></i><span>Gidrometriya</span>
          </a>
        </li>
        <li>
          <a href="{% url "hydrometeorological:meteostation-show" %}">
            <i class="bi bi-circle"></i><span>Meteorologiya</span>
          </a>
        </li>
      </ul>
    </li><!-- End Components Nav -->

  </ul>

</aside><!-- End Sidebar-->

templates/components/header.html
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <!-- <a href="index.html" class="logo d-flex align-items-center">
        <img src="assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">NiceAdmin</span>
      </a> -->
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

  
    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
  
        <li class="nav-item dropdown pe-3">
  
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ request.user.username }}</span>
          </a><!-- End Profile Iamge Icon -->
  
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
  
            <li>
              <a class="dropdown-item d-flex align-items-center" href="/admin">
                <i class="bi bi-person"></i>
                <span>Admin panel</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
  
            <li>
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button class="dropdown-item d-flex align-items-center" type="submit">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Chiqish</span>
                </button>
              </form>
              <!-- <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a> -->
            </li>
  
          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->
  
      </ul>
    </nav><!-- End Icons Navigation -->
  
  </header><!-- End Header -->

templates/components/loading_modal.html
<div class="modal" id="loadingModal" tabindex="-1" role="dialog" aria-labelledby="loadingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">
                <div class="spinner-border text-primary" role="status">
                    <span class="sr-only"></span>
                </div>
                <p class="mt-2">Yuklanmoqda...</p>
            </div>
        </div>
    </div>
</div>

<script>
    function showLoading() {
        $('#loadingModal').modal('show');
    }
    
    function hideLoading() {
        $('#loadingModal').modal('hide');
    }
</script>

templates/components/message-success.html
{% if messages %}
<div class="toast-container position-fixed top-0 p-5 start-50 translate-middle-x">
  <div id="successToast" class="toast text-bg-info p-0 m-0" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body">
        {% for message in messages %}
            <p class="p-0 m-0">{{ message }}</p>
        {% endfor %}
      </div>
      <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>

  {% if form.errors %}
  {% for message in form.errors %}
  <div class="toast text-bg-info p-0 m-0 form-toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body">
        <p class="p-0 m-0">{{ message.message }}</p>
      </div>
      <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
  {% endfor %}
  {% endif %}

<div class="toast-container position-fixed top-0 p-5 start-50 translate-middle-x">
  
</div>
{% endif %}

{% block scripts %}
{% if messages %}
<script>
  bootstrap.Toast.getOrCreateInstance(document.getElementById('successToast')).show()
</script>
{% endif %}
{% if form.errors %}
<script>
  $.each($('.form-toast'), function(toast){
    bootstrap.Toast.getOrCreateInstance(toast).show()  })
</script>
{% endif %}
{% endblock scripts %}

templates/components/modals.html
{% if modal == 'hydrogeological' %}
<div class="modal fade" id="hydrogeologicalPasportModal" tabindex="-1" aria-labelledby="hydrogeologicalPasportModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-custom">
    <div class="modal-content">
      <div class="modal-header">
        <!-- <h1 class="modal-title fs-5" id="exampleModalLabel">Jadval</h1> -->
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table table-bordered well">
          <thead>
            <tr>
              <th scope="col">Tashkilot</th>
              <th scope="col">Stansiya</th>
              <th scope="col">Qudug' Raqami</th>
              <th scope="col">Qudug' Turi</th>
              <th scope="col">Viloyat</th>
              <th scope="col">Tuman</th>
              <th scope="col" style="width: 15%">Mo'ljal</th>
              <th scope="col">Joylashuv o'rni</th>
              <th scope="col">To'ldirilgan sanasi</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            </tr>
          </tbody>
        </table>
        <table class="table table-bordered coordinate mb-0">
          <thead>
            <tr>
              <th scope="col">Qudug' raqami</th>
              <th scope="col" colspan="3" class="text-center">Shimoliy kenglik ( ° ' " )</th>
              <th scope="col" colspan="3" class="text-center">Sharqiy uzunlik ( ° ' " )</th>
              <th scope="col">x</th>
              <th scope="col">y</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if modal == 'hydromelioratical' %}
<div class="modal fade" id="hydromelioraticalPasportModal" tabindex="-1" aria-labelledby="hydromelioraticalPasportModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-custom">
    <div class="modal-content">
      <div class="modal-header">
        <!-- <h1 class="modal-title fs-5" id="exampleModalLabel">Jadval</h1> -->
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table table-bordered well">
          <thead>
            <tr>
              <th scope="col">Tashkilot</th>
              <th scope="col">Ekspeditsiya</th>
              <th scope="col">Qudug' Raqami</th>
              <th scope="col">Qudug' Turi</th>
              <th scope="col">Viloyat</th>
              <th scope="col">Tuman</th>
              <th scope="col" style="width: 15%">Mo'ljal</th>
              <th scope="col">Joylashuv o'rni</th>
              <th scope="col">To'ldirilgan sanasi</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            </tr>
          </tbody>
        </table>
        <table class="table table-bordered coordinate mb-0">
          <thead>
            <tr>
              <th scope="col">Qudug' raqami</th>
              <th scope="col" colspan="3" class="text-center">Shimoliy kenglik ( ° ' " )</th>
              <th scope="col" colspan="3" class="text-center">Sharqiy uzunlik ( ° ' " )</th>
              <th scope="col">x</th>
              <th scope="col">y</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if modal == 'fullscreenmodal' %}
<div class="modal fade" id="fullscreenModal" tabindex="-1" aria-labelledby="fullscreenModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen">
      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="modalBody">
              <!-- Table content will be inserted here -->
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
          </div>
      </div>
  </div>
</div>
{% endif %}

{% if modal == 'imagedownloadmodal' %}
<div class="modal fade" id="blobImageModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="blobImageModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body overflow-auto" >
              <!-- Table content will be inserted here -->
            <div class="d-flex align-items-center ">
              <img
                src=""
                style='max-height:50vh'
                class="mx-auto"
                alt=""
              />
            </div>
          </div>
          <div class="modal-footer">
              <a href='' class="btn btn-primary me-auto">Yuklash</a>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
          </div>
      </div>
  </div>
</div>
{% endif %}

templates/components/navbar.html
{% comment %} <header id="header" class="header d-flex align-items-center shadow-none" style="background-color: transparent">
  <nav class="header-nav w-100">
    <ul class="d-flex align-items-center w-100">
      {% if title %}
      <li class="nav-item pe-3 me-auto">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="{% url url %}">
          <h3 class="px-0 py-2 m-0"> <i class="bi bi-arrow-left-circle-fill"></i> {{ title }}</h3>
        </a>
      </li>
      {% endif %}
      <li class="nav-item dropdown pe-3 ms-auto">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#dropdown" data-bs-toggle="dropdown">
          <span class="btn btn-outline-primary px-4 py-2 rounded-5 d-md-block dropdown-toggle">{{ user.get_username }}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile m-0">
          <li>
            <a class="dropdown-item d-flex align-items-center" href="/admin">
              <i class="bi bi-person"></i>
              Admin Panelga kirish
            </a>
          </li>
          <li>
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button class="dropdown-item d-flex align-items-center" type="submit">
                <i class="bi bi-box-arrow-right"></i>
                <span>Chiqish</span>
              </button>
            </form>
          </li>
          
        </ul>
      </li>
    </ul>
  </nav>
</header> {% endcomment %}


<div class="pagetitle">
    {% if title %}
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="{% url url %}">
          <h1 class="px-0 py-2 m-0"> <i class="bi bi-arrow-left-circle-fill"></i> {{ title }}</h1>
        </a>
    {% endif %}
    <!-- <h1>Dashboard</h1> -->
    <!-- <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
      </ol>
    </nav> -->
  </div><!-- End Page Title -->

templates/components/pagination.html
{% load custom_tags %}

<footer class="footer">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
            {% if page == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="?{% param_replace page=page %}">{{ page }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=page %}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
        
      </ul>
    </nav>
  </footer>